# Generated by Django 3.2.5 on 2021-07-11 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingredients', '0001_initial'),
        ('recipes', '0003_auto_20210711_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_in_shopping_cart',
                 models.BooleanField(blank=True, default=False, verbose_name='is in shopping cart')),
                ('is_favorited', models.BooleanField(blank=True, default=False, verbose_name='is in favorites')),
                ('added_to_favorites', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('added_to_shopping_cart', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
            ],
            options={
                'verbose_name': 'Favorites',
                'verbose_name_plural': 'Favorites',
                'ordering': ['-added_to_favorites', '-added_to_shopping_cart'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='measurementunit',
            unique_together=None,
        ),
        migrations.AlterField(
            model_name='ingredientamount',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_amounts', to='ingredients.ingredient', verbose_name='ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.IngredientAmount', to='ingredients.Ingredient', verbose_name='ingredients'),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='MeasurementUnit',
        ),
    ]
