# Generated by Django 3.2.5 on 2021-07-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210719_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouriterecipe',
            name='is_favorited',
            field=models.BooleanField(default=False, verbose_name='is in favorites'),
        ),
        migrations.AlterField(
            model_name='favouriterecipe',
            name='is_in_shopping_cart',
            field=models.BooleanField(default=False, verbose_name='is in shopping cart'),
        ),
        migrations.AlterUniqueTogether(
            name='favouriterecipe',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ingredientamount',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='favouriterecipe',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_favorite_recipe'),
        ),
        migrations.AddConstraint(
            model_name='ingredientamount',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_recipe_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('author', 'name'), name='unique_recipe_author'),
        ),
    ]
