# Generated by Django 3.2.5 on 2021-07-11 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('metric', models.CharField(choices=[('mass', 'mass'), ('volume', 'volume'), ('quantity', 'quantity')], max_length=255, verbose_name='metric')),
            ],
            options={
                'verbose_name': 'Measurement unit',
                'verbose_name_plural': 'Measurement units',
                'ordering': ['metric', 'name'],
                'unique_together': {('name', 'metric')},
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('measurement_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='ingredients.measurementunit', verbose_name='ingredients')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'ordering': ['measurement_unit', 'name'],
                'unique_together': {('name', 'measurement_unit')},
            },
        ),
    ]
