# Generated by Django 3.2.5 on 2021-07-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_alter_ingredient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementunit',
            name='metric',
            field=models.CharField(choices=[('mass', 'mass'), ('volume', 'volume'), ('quantity', 'quantity'), ('percent', 'percent'), ('miscellaneous', 'miscellaneous')], max_length=255, verbose_name='metric'),
        ),
    ]
