# Generated by Django 3.2.5 on 2021-07-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0005_alter_measurementunit_metric'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name', 'measurement_unit'], 'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='measurementunit',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='unique_ingredient_unit'),
        ),
        migrations.AddConstraint(
            model_name='measurementunit',
            constraint=models.UniqueConstraint(fields=('name', 'metric'), name='unique_measurement_metric'),
        ),
    ]
